# Generated by Django 4.2.4 on 2023-09-21 06:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_tag_fooddetail_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetail',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='fooddetail',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_detail', to='food.food'),
        ),
        migrations.AlterField(
            model_name='fooddetail',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='food_detail', to='food.tag'),
        ),
    ]
