# Generated by Django 4.1 on 2024-05-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_fooddetail_content_alter_fooddetail_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetail',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags_detail', to='food.tag'),
        ),
    ]
