# Generated by Django 4.1 on 2024-06-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_commnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
