# Generated by Django 4.1 on 2024-06-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_rename_commnet_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='food_detail_commet',
            new_name='food_detail_comment',
        ),
    ]
