# Generated by Django 4.1 on 2024-07-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_rename_food_detail_commet_comment_food_detail_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='food_detail_comment',
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags_detail', to='food.tag'),
        ),
        migrations.DeleteModel(
            name='FoodDetail',
        ),
    ]
