# Generated by Django 4.1 on 2024-07-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_remove_comment_food_detail_comment_food_tags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
